- name: variables
  hosts: web
  vars: 
    Name: "Salman"
    Age: "25"
    Born: "1999"
  tasks:
    - name: Print the variables
      ansible.builtin.debug:
        msg: "My name: {{Name}} Age: {{Age}} Born: {{Born}}"
